language: node_js
os:
- osx

node_js:
- '13'

cache: yarn

env:
  global:
    secure: cguim9AJLJRDFePb7C42YCOoEeuox6PlChwPPOMvzgv/GmKEWlbF8DKkbL0r1lcgVepxOVZd6ysPq35uWpuaBt9I/6+zPhxsck5In8wrylBV+eYE20U7d+73VfJTJnqxk4gSsbpG1v2xQiXGF6NMmC4hllPtHEHViWtNv0CtbJm1yddPB2CxD6a6LsEN/J9IHio5roiDX9wW5X7PiYyZNELN8FjOsPLD4xgpJpsdPrSBk7bEG9gU5BCAkj9FYyS87hZ4zdNJ7J97V4mdaTW49CuwPVa2kZWcET1yORoVXEinW0dvsh+BZNi29Msfu46yqvN9Xvicl97sREYTWUYQM9K3wJXnSPfBku6NjkS+x+VFfxakY0E79CWgV1Bo9Q99e17yqtRqpq0R33ZPhDRfHyJJDl6IzLo3Xp+rL+Ho96Jj+Jui7bsgCh9mkWvpSh/JAkNPto11HuYyV/nPFil9b+UhOjLaVyrjza9+8QB1COi+lShX5XnSp5EekXPi+6Dv+IPRi93eluT8a/h5IDmxReV7QrSfmu8bkVbLxT/LC5QUsjBaeDl/r8cyvyqTNyOAqbIfuLwjEfurb0Rqb+yaAXlTTyp60iGnLEE3UtCX2NLiAZ72/Y8qJuriuLtZnqYSJzgEKcdoUWyh9YyTpRk1P+UVCoFfGgeQQqtgS/OkzJ8=

jobs:
  include:
    - stage: greenkeeper
      name: "GreenKeeper"
      script: greenkeeper-lockfile-update
      before_install: yarn global add greenkeeper-lockfile@1
      after_script: greenkeeper-lockfile-upload
      if: branch = development

    - stage: deploy
      name: "Deploy"
      script: yarn build
      if: branch = master
